apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: reversewords-all-app
  namespace: gitops-apps
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - reversewords-all-app
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: reversewords-all-app-subscription
  namespace: gitops-apps
  labels:
    app: reversewords-all-app
  annotations:
    apps.open-cluster-management.io/github-path: apps/reversewords/
    apps.open-cluster-management.io/github-branch: prod
spec:
  channel: gitops-apps/mvazquez-gitops-github
  placement:
    placementRef:
      kind: PlacementRule
      name: all-okay-clusters
