apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: finance-dev-clusters
  namespace: gitops-apps
spec:
  clusterConditions:
   - type: OK
  clusterSelector:
    matchExpressions: []
    matchLabels:
      finance: "dev"
  clusterReplicas: 1
