apiVersion: policy.mcm.ibm.com/v1alpha1
kind: Policy
metadata:
  name: policy-deployment-inform
  namespace: policies
  annotations:
    policy.mcm.ibm.com/standards: 
    policy.mcm.ibm.com/categories: 
    policy.mcm.ibm.com/controls: 
spec:
  complianceType: musthave
  remediationAction: inform
  disabled: false
  namespaces:
    exclude: ["kube-*"]
    include: ["openshift-monitoring"]
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: cluster-monitoring-operator
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementBinding
metadata:
  name: binding-policy-deployment-inform
  namespace: policies
placementRef:
  name: placement-policy-deployment-inform
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-deployment-inform
  kind: Policy
  apiGroup: policy.mcm.ibm.com
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-deployment-inform
  namespace: policies
spec:
  clusterConditions:
  - type: OK
  clusterSelector:
    matchExpressions:
      - {key: env, operator: In, values: ["pro"]}
